syntax on
set number
set cindent
set smartindent
set showmatch
set ruler
:set mouse=a
:set backspace=indent,eol,start



set tags=./.tags;,.tags     

call plug#begin('~/.vim/plugged')
" Plug 'universal-ctags/ctags'
Plug 'preservim/nerdtree'
Plug 'ludovicchabant/vim-gutentags'
call plug#end()

so ~/.vim/init.vim
